config/routes.rb
Rails.application.routes.draw do
  devise_for :podcasts
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay)}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcastfm</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>

  <body>
    <% if notice %>
    <p class="notice">
      <%= notice %>
    </p>
    <% elsif alert %>
    <p class="alert">
      <%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="background">
   <header class="cf">
     <div class="wrapper_wide">
       <a href="#" id="logo">Podcast.fm</a>
       <nav>
         <ul>
           <%unless podcast_signed_in? %>
             <li><a href="#">Explore</a></li>
             <li><%=link_to "Sign In", new_podcast_session_path%></li>
             <li><%=link_to "Create a Podcast", new_podcast_registration_path %></li>
           <% else %>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Explore</a></li>
            <li><%=link_to "Sign Out", destroy_podcast_session_path, method: :delete%></li>
          <% end %>
         </ul>
       </nav>
     </div>
   </header>
   <div class="wrapper_skinny">
     <h1>Discover your new favorite<br> podcast, or create your own.</h1>
     <%=link_to "Create a Podcast", new_podcast_registration_path, class: "button button_highlight" %>
     <%=link_to "Explore", new_podcast_registration_path, class: "button button_white" %>
   </div>
</div>